### ISSUE TITLE
Setup stops at vswitch

### ISSUE THREAD

**Issue by McNairy** [DeploymentsBook/puppet-deployments#19]
ERROR    -> Unable to manage Puppetfile content 'vswitch': Could not resolve desired ref 'stable/liberty' and no default given

Since I'm trying to install mitaka I find the "stable/liberty" reference odd.

Per the book recomendation I'm installing OpenStack on a fresh Ubuntu 14.04.2 LTS release in a VirtualBox VM on a Kubuntu 16.04 host.

**Comment by pleia2** [comment]
We were using the liberty version of the vswitch module intentionally (I'll look through my notes to refresh my memory as to why), but it looks like it's now been deprecated due to that version no longer being supported upstream as of a few days ago (February 16th).

I haven't tested it, but to get you going you can give editing the Puppetfile in the puppet-data repository a go to update Line 110 to be stable/mitaka a try:

https://github.com/DeploymentsBook/puppet-data/blob/master/Puppetfile#L110

I'll work to make time ASAP to test this on my end to test and push a fix to the repository.

**Comment by McNairy** [comment]
I am impressed with your response time, thank you for that. I tried updating the Puppetfile but it gives the same error. Perhaps Puppet has the file cached (I have no Puppet knowledge)?

**Comment by pleia2** [comment]
Yeah, You'll want to edit the Puppetfile that was placed somewhere in the /etc/puppet. Forgive me for not having the exact location off hand, hopefully you can find it! Otherwise I'll update when I get back to my testing system in a bit.

**Comment by McNairy** [comment]
Ah, that did it. The file is /etc/puppet/Puppetfile#L112.

Thank you. Will continue through book later in the day.

**Comment by matthewfischer** [comment]
I think maybe that mitaka wasn't released yet for that module or there was an error on trunk. If it's better now we can switch it.

**Comment by McNairy** [comment]
I tried "sudo puppet apply" but it failed with many errors. Looking at the puppet_apply_foundations.log it doesn't look like any databases are being created.

^[[mNotice: /Stage[main]/Glance::Db::Sync/Exec[glance-manage db_sync]/returns: 2017-02-20 18:31:55.597 2576 CRITICAL glance [-] OperationalError: (pymysql.err.OperationalError) (1045, u"Access denied for user 'glance'@'localhost' (using password: YES)")^[[0m

[[mNotice: /Stage[main]/Nova::Db::Sync/Exec[nova-db-sync]/returns: error: (pymysql.err.OperationalError) (1045, u"Access denied for user 'nova'@'localhost' (using password: YES)")^[[0m

When I login to the mysql server with the same password I entered into /etc/puppet/hiera/common.yaml for the database server there are no databases created.

**Comment by pleia2** [comment]
Matt might be able to chime in here, but while these puppet apply changes should be able to run independently, it could be that it got in a state where it believes a previous puppet apply run created the databases.

Can you create a different issue for this so we can close out this vswitch one and chase this up independently?

**Comment by matthewfischer** [comment]
Yeah those don't appear to be related to ovs OR the vswitch issue caused an earlier catalog failure that propagated down to this.
